backend-test:
  image: registry.gitlab.com/nccu_se_2025/pilaopan/auto-scheduling-system:latest
  stage: test
  tags: [gcp]
  cache:
    paths:
      - .venv/
  script:
    - cd Backend
    - export PYTHONPATH=$(pwd) 
    - pip install -r requirements.txt
    - pytest --cov=. --cov-report=term-missing --cov-report=html | tee ../backend-coverage.txt
  artifacts:
    paths:
      - backend-coverage.txt
      - Backend/htmlcov/
    expire_in: 1 week
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
backend-build:
  image: docker:latest
  stage: build
  tags: [gcp]
  cache:
    paths:
      - .venv/
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd Backend
    - export PYTHONPATH=$(pwd)
    - docker build -t backend-server .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'